typography_spectrum: 0.2384861537721008
color:
  brandStrength: 0.8477495815604925
  lightness: 0.9584958245977759
  saturation: 0.6426843816880137
  rhythmicContrast: 0.5979812417645007
  brandColors:
    - '#FFFFFF'
    - '#303636'
    - '#949381'
    - '#FDB45A'
    - '#C8CBD0'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/6b7f12aa-f4ef-44f3-860b-3af824b7e913.jpg
layout_spectrum: 0.21919734263792634
analytics:
  google: UA-56165495-1
author:
  name: Ursin Saluz
  email: ursin.saluz@gmail.com
  url: www.alvier.ch
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7bda2f1b-3fde-4e64-8317-77b60a4bc9ec.svg
name: Schellenurs.li
navigation:
  - name: Gadgets
    id: df895105-28f0-4ce5-a3c4-02c84995971e
    type: content
  - name: Reisen
    id: aaca4c44-51c0-4a96-b274-5e0cf4bcf47b
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5dbf4f49-5d6b-468f-bd40-028edb3ef10f.svg
title: Schellenursli
description: Welcome to my world
